### PR TITLE
Avoid hardcoding binary paths

### PR DESCRIPTION
**Pull request by rvolosatovs**
`bash` is not guaranteed to be available at `/bin/bash` or it may be outdated, e.g. on MacOS, the `/bin/bash` binary is extremely outdated and often users have another `bash` installed via package manager, which is then located at a different path, on NixOS `/bin/bash` does not exist at all:
```
$ ls -alh /bin       
total 4.0K
drwxr-xr-x 1 root root   4 Apr  9 11:57 .
drwxr-xr-x 1 root root 112 Feb  9 20:40 ..
lrwxrwxrwx 1 root root  75 Apr  9 11:57 sh -> /nix/store/lb3hli8d9536g45mndwfwyi6fpny0blh-bash-interactive-4.4-p23/bin/sh
```

Using `/usr/bin/env bash` is way more portable and provides expected results more often than `/bin/bash`, hence fix that.

### CODE REVIEW

**Comment by zvldz** [comment]
Doubtful change.
I didn't have a problem with macos.
I'll think about it.

**Comment by rvolosatovs** [comment]
> Doubtful change.

Why so? Is portability and cross-platform support not a goal of this project?

**Comment by zvldz** [comment]
I personally had no problem with bash on MacOS.
But fuse-ext2 had a problem. I have to test it to make sure nothing breaks on different OSes.

**Comment by rvolosatovs** [comment]
This definitely works as-is on MacOS, however, in it's current state this project is unusable on NixOS (as I stated in OP), I'd expect the same also on Guix and there are definitely other distributions/OSes, which do not have `/bin/bash` available by default.
Less severe issue is that the user would expect `bash` from their `PATH` being executed, which may or may not be `/bin/bash`

**Comment by zvldz** [comment]
> See also, for example, this article https://www.cyberciti.biz/tips/finding-bash-perl-python-portably-using-env.html

Yeah, I know about that. 
Okay, I'll just add it.
Thank you for the pull request.

**Pull request merged**
