### PR TITLE
Fix valetudo-daemon.sh

### PR DESCRIPTION
**Pull request by cryptomilk**
```
/usr/local/bin/valetudo-daemon.sh: exec: line 30:
VALETUDO_CONFIG_PATH=/mnt/data/valetudo/valetudo_config.json: not found
```

### CODE REVIEW

**Comment by pidator** [comment]
You're just reverting the changes made by @Hypfer in PR https://github.com/zvldz/vacuum/pull/54. What Valetudo version (vanilla/RE and version-number) are you trying to run? Afaik the env variable is needed for newer Valetudo vanilla versions (>0.6) to run, so you'll have to set the variable depending on the selected valetudo version...

**Comment by zvldz** [comment]
I missed  PR, I will check problem

**Comment by zvldz** [comment]
I fixed it.
https://github.com/zvldz/vacuum/commit/5a091ad36458212a749ab371449fcc27c07b2424

**Comment by zvldz** [comment]
@cryptomilk 
Thank you fou PR
But I've changed it a bit

**Pull request closed without merging**
