### PR TITLE
Add sound removal script

### PR DESCRIPTION
**Pull request by Poeschl**
Added script to remove all non-english sound files.

This helped me to use the 2008 firmware with my custom soundpack. Without the removal I ran into `not enough space` errors. It saves around 50 MiB.

### CODE REVIEW

**Comment by zvldz** [comment]
Why "if [ $ENABLE_DNS_CATCHER -eq 1 ]; then" ?

**Comment by Poeschl** [comment]
Whups, a leftover. Sry

**Comment by Poeschl** [comment]
Should be better now

**Comment by zvldz** [comment]
Please add
`CLEANUP_SOUNDFILES=${CLEANUP_SOUNDFILES:-"0"}`
after 
`LIST_CUSTOM_FUNCTION+=("custom_function_cleanup_sound")`

Also the name of the parameter may need to be changed to something else.
For example:
--remove-non-en-sounds
--remove-asian-sounds
--remove-extras-sounds
imo

**Comment by zvldz** [comment]
Thanks for PR

**Comment by Poeschl** [comment]
Thanks for the fast feedback 👍

**Pull request merged**
