### PR TITLE
Added custom script to protect access point with a PSK

### PR DESCRIPTION
**Pull request by aaronk6**
Prevent robot from opening an unprotected Wifi.

### CODE REVIEW

**Comment by zvldz** [comment]
It won't work on 2008+ firmware.
Some additional checks must be done.
And it's better to adapt for 2008+ firmware as well.

Alternatively, it is possible to create firmware with key --unprovisioned

**Comment by aaronk6** [comment]
Hi,

Thanks for looking into this!

> It won't work on 2008+ firmware.
> Some additional checks must be done.

What kind of checks? Is there an example I could learn from?

> Alternatively, it is possible to create firmware with key --unprovisioned

I did this, but this will still leave an open access point for 200 seconds after each boot. So this is why I thought it would be useful to protect the default AP.

**Comment by zvldz** [comment]
> What kind of checks? Is there an example I could learn from?

The simplest firmware check for 2008+ is the existence of the file /etc/inittab

**Comment by zvldz** [comment]
I'll try to implement it for all types of firmware later. It's an interesting idea.

**Comment by aaronk6** [comment]
Cool, thanks for merging this!

**Comment by zvldz** [comment]
Thank you for PR.

**Pull request merged**
